export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR';
export const SHOW_ORDER = 'SHOW_ORDER';
export const CLOSE_ORDER = 'CLOSE_ORDER';

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const CLOSE_DETAILS = 'CLOSE_DETAILS';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REPLACE_INGREDIENT = 'REPLACE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const CALCULATE_PRICE = 'CALCULATE_PRICE';
export const RESET_STATE = 'RESET_STATE';
